VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsS1000DIssueDate"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'=========================================================
'
' MRJ BR‚Ì’è‹`‚É]‚¢ Issue Date‚ğˆ—‚·‚éƒNƒ‰ƒX
'
'
' Hideaki Takahashi
' ///// 2014/03/18 /////
'
'
'
'=========================================================
Option Explicit

