VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "clsS1000DFormat"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'=========================================================
'
' S1000Dの定義に従い S1000D_FORMAT(拡張子)を処理するクラス
'
'
' Hideaki Takahashi
' ///// 2014/03/18 /////
'
'
'
'=========================================================
Option Explicit
'
'Dim S1000D_FORMAT_Index_ As S1000D_FORMAT
'Dim S1000D_FORMAT_ As String * 3
'
'Property Let S1000D_FORMAT(ByVal S1000D_FORMAT_Index As S1000D_FORMAT)
'    S1000D_FORMAT_Index_ = S1000D_FORMAT_Index
'    S1000D_FORMAT_ = GetS1000DExtension(S1000D_FORMAT_Index)
'End Property
'
'Property Get S1000D_FORMAT() As String
'    S1000D_FORMAT = S1000D_FORMAT_
'End Property
'

